### ISSUE TITLE
What $TERM variable should we use?

### ISSUE THREAD

**Issue by Kabouik** [direc85/toeterm#8]
Should Toeterm be used with `TERM=xterm-color` or something else? This seems to solve most of the refreshing issues I'm experiencing when using `TERM=xterm-256color`, but I'm not sure that's optimal. 

Also, does Toeterm support 24-bit colours?

Thanks for your work!

**Comment by direc85** [comment]
Apparently ToeTerm uses `TERM=xterm-256color` but I really don't know what the options are and how they affect the terminal/console... I'll see if I can figure something out. Help appreciated...

**Comment by direc85** [comment]
Okay, it looks like `xterm-color` is a really different choice, but `xterm` is what many threads suggest... I wish I knew more about their impact!

I changed the default to `xterm` now in my code, but I haven't even pushed it yet. I also have to somehow make the application start/installation change the existing value in `~/.config/ToeTerm/settings.ini` without nuking the file first...

**Comment by direc85** [comment]
Well, using `xterm` doesn't help with the scrolling issues. I'll try `xterm-color` as you suggested...

**Comment by Olf0** [comment]
Triggered by this thread and being curious, I took a quick look (presumably far less research than @direc85 already did).
[This Stackexchange thread](https://stackoverflow.com/questions/10003136/what-is-the-difference-between-xterm-color-xterm-256color) indicates that `xterm-color` is not recommended and outdated, but hints that it may resolve compatibility issues as it uses a different configuration and code paths.  This is in line with @direc85's research.

But the main takeaway from this thread for me was the "infocmp" command (e.g.,`infocmp xterm-color xterm-256color`) and to study `man 5 terminfo`, as also indicated at one more normative [source (GNU gettext TERM variable)](https://www.gnu.org/software/gettext/manual/html_node/The-TERM-variable.html) (plus `msgcat --color=test` for testing terminal colours).
And this [Stackexchange posting](https://unix.stackexchange.com/a/198949) covers some related aspects of the TERM environment variable.

P.S.: What about the other classic values of `TERM`: `rxvt` / `rxvt-16color`, `konsole` / `konsole-16color` (IIRC Gnome Terminal and Konsole (the KDE terminal application) uses that) and `linux` (besides `xterm`, `xterm-16color`, `xterm-88color`, `xterm-256color`, plus `xterm-color`)?
Even the historic `vt220` allows for scrolling in all directions and colours (IIRC 8 or 16), and presumably uses a different config and code path, too.

**Comment by direc85** [comment]
To be honest, I don't have the knowledge to take this that much further... Fingerterm does the same buggy line editing at least, so the change must have come with some system library change. The wrong fix would be using `xterm-color` (which does not actually fix the issue, now that I tested it). The line scrolling issue should be fixed independently, and just use `xterm-256color` as before. What using `linux` would gain/lose, I have no reasonable sense.

**Comment by Kabouik** [comment]
I don't remember the exact testing I did when I initially posted this issue, but I believe using `xterm-color` was a (dirty and not fully working) fix for some terminal applications using ncurses, like cmus, nmail, and others. With `xterm-256color`, I believe I was getting issues with lines not refreshing properly and ultimately borking the view. That really does not mean that using `xterm-color` is advisable, as I think different terminals may be based on different norms, although some of those infocomp values share some common ground.

The same kind of compatibility mixups may happen when using tmux, especially for colour support, and to be frank this all looks like sorcery to me and I never truly understood what was the elegant solution.

**Comment by direc85** [comment]
I have constantly been running into this, both with Toeterm and Fingerterm... It turned out that using `vt220` fixes at least the `nano` scrolling text issue... This still doesn't lead me any closer to the answer, but to new questions:
* What are the real capabilities of Toeterm and/or Fingerterm?
* If they are not known, how can we find out?
* What do we lose by using `vt220`?

**Comment by direc85** [comment]
Okay, it seems that there are at least two culprits: `cbt=\E[Z` and `kcbt=\E[Z` - they both mean back tabulator. The easy way would be to supply a custom terminfo file, and the hard way would be implementing the ANSI escape sequence...

**Comment by direc85** [comment]
Fixed in commit [328cbd4](https://github.com/direc85/toeterm/commit/328cbd4931a988fc4861b96ac762ee54d4613857) in which you can also find testing scripts to test and compare various terminals. They are generated for 16-color, 256-color (Fingerterm) and 256-color+24bit direct color (ToeTerm 1.9.9) terminals.

I did (way too much) testing today, and it looks like the correct one to use (the best one I could find) is `xterm-direct256`. It is not shipped with Sailfish - because why would it - so at this point you have to manually copy the file to `~/.terminfo/x/` (if you don't dare put it in `/usr/share/terminfo/x/` as root like I did) and set `envVarTERM=xterm-direct256` to `~/.config/ToeTerm/settings.ini`.

I'll try to make it so that the compiled terminfo file gets installed in the home folder - that should suffice and be polite enough regarding rest of the OS.
